### ISSUE TITLE
Setup Project

### ISSUE THREAD

**Issue by Mutai-Gilbert** [abenaTenkorang/Capstone2#21]
- Add a note telling the reviewer how many people there are in your team - We are 2(two)
 @abenaTenkorang and @Mutai-Gilbert 
https://github.com/abenaTenkorang/Capstone2/projects/1

**Comment by AmaduKamara** [comment]
# Status: Invalid Submission ❌ ❌ ❌ 

Hi @Mutai-Gilbert,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that does not have a link to your project's issue. Kindly add the Issue link in your PR description and information about the number of students working on this project 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED ✔🍾🎉**
Hello @Mutai-Gilbert and @abenaTenkorang 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
